### ISSUE TITLE
JupyterHub log in issue

### ISSUE THREAD

**Issue by dtrupp** [forrestbao/MLClass#8]
I am trying to log in to the Jupyter Hub but the I can't figure out my username. It says its lastname.lastname and I tried it with my last name and it didn't work. I have tried a few different variations. Also the TAs' email is not on the syllabus so I am not positive what Roger Ge Luo's email is

**Comment by forrestbao** [comment]
Sorry for the trouble due to a typo. It should have been lastname.firstname. I just updated. 

The TA's emails have been long posted on Canvas https://canvas.iastate.edu/courses/76193/discussion_topics/749750
